[bar.default]
background_opacity = 0.0
capsule = true
capsule_thickness = 0.79999998584389687
center = [ "group:g2" ]
concave_edge_corners = false
end = [ "group:g3", "group:g4", "group:g5", "session" ]
font_family = "AtkynsonMono Nerd Font"
margin_edge = 6
margin_ends = 6
padding = 12
radius = 6
scale = 0.80000000447034836
shadow = false
start = [ "control-center", "group:g1", "workspaces" ]
thickness = 24

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "temp", "ram" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "clock" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g3"
    members = [ "audio_visualizer", "media" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g4"
    members = [ "volume", "input_volume", "battery" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g5"
    members = [ "tray", "notifications", "wallpaper" ]
    opacity = 1.0
    padding = 6.0

[brightness]
minimum_brightness = 0.04999999888241291

[control_center]
hidden_tabs = [ "weather", "calendar", "screen-time" ]

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 0.4999999888241291
concave_edge_corners = false
radius = 8

[location]
custom_schedule = true
sunrise = "07:00"
sunset = "20:00"

[nightlight]
enabled = true

[notification]
background_opacity = 0.4999999888241291

[osd]
background_opacity = 0.4999999888241291
orientation = "vertical"
position = "top_right"
position_vertical = "top_right"

[shell]
font_family = "AtkynsonMono Nerd Font Mono"
offline_mode = true
panel_anchor_bar = "default"
password_style = "random"
settings_window_translucent = true
telemetry_enabled = false

    [shell.animation]
    speed = 1.2000000178813934

    [shell.launcher]
    compact = true
    fetch_exchange_rates = false

        [shell.launcher.providers.windows]
        global = true

    [shell.panel]
    borders = false
    clipboard_position = "top_center"
    control_center_placement = "floating"
    control_center_position = "top_center"
    list_item_background = true
    open_near_click_control_center = true
    open_near_click_wallpaper = true
    polkit_position = "top_center"
    session_placement = "floating"
    session_position = "top_center"
    shadow = false
    transparency_mode = "glass"
    wallpaper_placement = "floating"
    wallpaper_position = "top_center"

[theme]
builtin = "Nord"
community_palette = "Oxocarbon"
mode = "auto"
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "btop", "foot", "gtk3", "gtk4", "hyprland", "kitty", "qt", "starship" ]

[wallpaper]
transition = [ "disc", "fade", "wipe" ]

    [wallpaper.default]
    path = "/home/colours/Pictures/Wallpaper/wallhaven-72woj3.jpg"

    [wallpaper.last]
    path = "/home/colours/Pictures/Wallpaper/wallhaven-72woj3.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/colours/Pictures/Wallpaper/wallhaven-72woj3.jpg"

[widget.battery]
show_label = false

[widget.caffeine]
capsule = true

[widget.clock]
anchor = true

[widget.cpu]
show_value = false

[widget.media]
album_art_only = true
hide_when_no_media = true
title_scroll = "on_hover"

[widget.ram]
show_value = false

[widget.temp]
show_value = false

[widget.tray]
hide_passive = false
match_adjacent_spacing = true
